name: jv_alma_cis
description: A Flutter web app for JV ALMA CIS showcasing its divisions.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.14.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  video_player: ^2.9.1
  font_awesome_flutter: ^10.7.0
  logger: ^2.4.0
  url_launcher: ^6.3.0
  http: ^1.4.0
  fl_chart: ^1.0.0
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  file_picker: ^10.1.9
  webview_flutter: ^4.9.0
  go_router: ^15.1.2
  lucide_icons: 0.257.0
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  flutter_animate: ^4.5.2
  visibility_detector: ^0.4.0+2
  google_fonts: ^6.1.0
  path_provider: ^2.1.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/company_video.mp4
    - assets/images/company_background.jpg  
       
    - assets/certificates/
    - assets/images/agribusiness/
    - assets/images/construction/
    - assets/images/tic/
    - assets/images/clients/
    - assets/news/
    - assets/apk/
    - assets/images/subsidiaries/